/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.SGE;

/**
 *
 * @author joaocosta
 */
public class ResultadoPresidencial extends javax.swing.JFrame {
  private final int idEleicao;
  private final SGE sge;

  public ResultadoPresidencial (SGE sge, int idEleicao) {
    initComponents();
    
    this.idEleicao  = idEleicao;
    this.sge        = sge;
    this.setTitle("Eleições Presidenciais");
    
    setResultados();
  }
  
  /**
   * Creates new form ResultadoPresidenciais
   */
  public ResultadoPresidencial() {
    initComponents();
    this.setTitle("Eleições Presidenciais");
    this.idEleicao = 0;
    this.sge = null;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

      jMenu1 = new javax.swing.JMenu();
      returnButton = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      jScrollPane2 = new javax.swing.JScrollPane();
      jTable2 = new javax.swing.JTable();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      totalVotosR1 = new javax.swing.JLabel();
      votosValidosR1 = new javax.swing.JLabel();
      votosBrancosR1 = new javax.swing.JLabel();
      votosNulosR1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jLabel12 = new javax.swing.JLabel();
      votosValidosR2 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      votosNulosR2 = new javax.swing.JLabel();
      votosBrancosR2 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      totalVotosR2 = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      vencedorTextField = new javax.swing.JLabel();

      jMenu1.setText("jMenu1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(800, 600));

      returnButton.setText("< Voltar");
      returnButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          returnButtonActionPerformed(evt);
        }
      });

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeira Ronda"));

      jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
              {"Pedro Fernandes de Carvalho", "30%"},
        {"José Antunes Guimarães", "35%"},
        {"Fernando Manuel da Silva Ortiga", "35%"},
        {null, null}
            },
            new String [] {
              "Nome do Candidato", "Percentagem de Votos"
            }
            ) {
        boolean[] canEdit = new boolean [] {
          false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
          return canEdit [columnIndex];
        }
      });
      jScrollPane2.setViewportView(jTable2);

      jLabel2.setText("Votos Nulos:");

      jLabel3.setText("Votos Brancos:");

      jLabel4.setText("Votos Válidos:");

      jLabel5.setText("Número total de votos:");

      totalVotosR1.setText("5000000");

      votosValidosR1.setText("4000000");

      votosBrancosR1.setText("600000");

      votosNulosR1.setText("400000");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
          jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel5)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(totalVotosR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(votosBrancosR1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(votosValidosR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jScrollPane2)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addGap(82, 82, 82)
                    .addComponent(votosNulosR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())))
                );
      jPanel1Layout.setVerticalGroup(
          jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(totalVotosR1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(votosValidosR1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(votosBrancosR1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(votosNulosR1))
            .addContainerGap(16, Short.MAX_VALUE))
          );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segunda Ronda"));

      jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
              {"Fernando Manuel da Silva Ortiga", "55%"},
        {"José Antunes Guimarães", "45%"},
        {null, null},
        {null, null}
            },
            new String [] {
              "Nome do Candidato", "Percentagem de Votos"
            }
            ) {
        boolean[] canEdit = new boolean [] {
          false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
          return canEdit [columnIndex];
        }
      });
      jScrollPane1.setViewportView(jTable1);

      jLabel12.setText("Votos Brancos:");

      votosValidosR2.setText("3000000");

      jLabel13.setText("Votos Nulos:");

      votosNulosR2.setText("250000");

      votosBrancosR2.setText("250000");

      jLabel11.setText("Votos Válidos:");

      jLabel10.setText("Número total de votos:");

      totalVotosR2.setText("3500000");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10)
                  .addComponent(jLabel12)
                  .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(totalVotosR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10))
                  .addComponent(votosBrancosR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(votosValidosR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(82, 82, 82)
                .addComponent(votosNulosR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
            );
      jPanel2Layout.setVerticalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel10)
              .addComponent(totalVotosR2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel11)
              .addComponent(votosValidosR2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel12)
              .addComponent(votosBrancosR2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel13)
              .addComponent(votosNulosR2))
            .addContainerGap())
          );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vencedor"));

      vencedorTextField.setText("Fernando Manuel da Silva Ortiga");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
          jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencedorTextField)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
      jPanel3Layout.setVerticalGroup(
          jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(vencedorTextField)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(returnButton)
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
          );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(returnButton)
            .addContainerGap())
          );

      pack();
    }// </editor-fold>//GEN-END:initComponents

  /** Preencher campos de votos. */
  public void setResultados () {
    // TODO: Apresentar o vencedor.
    
    // Votos da 1ª ronda.
    totalVotosR1.setText("" + sge.votosTotaisPresidencial(idEleicao, 1));
    votosNulosR1.setText("" + sge.votosNulosPresidencial(idEleicao, 1));
    votosBrancosR1.setText("" + sge.votosBrancosPresidencial(idEleicao, 1));
    
    // Votos da 2ª ronda.
    totalVotosR2.setText("" + sge.votosTotaisPresidencial(idEleicao, 2));
    votosNulosR2.setText("" + sge.votosNulosPresidencial(idEleicao, 2));
    votosBrancosR2.setText("" + sge.votosBrancosPresidencial(idEleicao, 2));
  }

  /**
   * Voltar para o menu inicial.
   */
  private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
    // Voltar para o ecrã de login.
    Login login = new Login();
    login.setLocationRelativeTo(this);
    this.dispose();
    login.setVisible(true);
  }//GEN-LAST:event_returnButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
      javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception ex) {
      System.out.println("Unable to load native look and feel");
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ResultadoPresidencial().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTable jTable2;
  private javax.swing.JButton returnButton;
  private javax.swing.JLabel totalVotosR1;
  private javax.swing.JLabel totalVotosR2;
  private javax.swing.JLabel vencedorTextField;
  private javax.swing.JLabel votosBrancosR1;
  private javax.swing.JLabel votosBrancosR2;
  private javax.swing.JLabel votosNulosR1;
  private javax.swing.JLabel votosNulosR2;
  private javax.swing.JLabel votosValidosR1;
  private javax.swing.JLabel votosValidosR2;
  // End of variables declaration//GEN-END:variables
}
