/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.Candidato;
import Business.Eleicao;
import Business.SGE;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaocosta
 */
public class ResultadoPresidencial extends javax.swing.JFrame {
  private final Eleicao eleicao;
  private final SGE sge;

  public ResultadoPresidencial (SGE sge, Eleicao e) {
    initComponents();
    
    this.eleicao  = e;
    this.sge      = sge;
    
    this.setTitle(eleicao.toString());
    setResultados();
  }
  
  /**
   * Creates new form ResultadoPresidenciais
   */
  public ResultadoPresidencial() {
    initComponents();
    this.setTitle("Eleições Presidenciais");
    this.eleicao  = null;
    this.sge      = null;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenu1 = new javax.swing.JMenu();
    returnButton = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    totalVotosR1 = new javax.swing.JLabel();
    votosBrancosR1 = new javax.swing.JLabel();
    votosNulosR1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    candidatosR1 = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    abstencaoR1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    votosNulosR2 = new javax.swing.JLabel();
    votosBrancosR2 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    totalVotosR2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    candidatosR2 = new javax.swing.JTable();
    jLabel4 = new javax.swing.JLabel();
    abstencaoR2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    vencedorTextField = new javax.swing.JLabel();

    jMenu1.setText("jMenu1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(800, 600));

    returnButton.setText("< Voltar");
    returnButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        returnButtonActionPerformed(evt);
      }
    });

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeira Ronda"));

    jLabel2.setText("Votos Nulos:");

    jLabel3.setText("Votos Brancos:");

    jLabel5.setText("Número total de votos:");

    totalVotosR1.setText("0");

    votosBrancosR1.setText("0");

    votosNulosR1.setText("0");

    candidatosR1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Candidato", "Nº Candidato", "Votos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(candidatosR1);

    jLabel1.setText("Abstenção: ");

    abstencaoR1.setText("0%");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addComponent(totalVotosR1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(abstencaoR1)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addGap(70, 70, 70)
            .addComponent(votosBrancosR1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(82, 82, 82)
            .addComponent(votosNulosR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(totalVotosR1)
          .addComponent(jLabel1)
          .addComponent(abstencaoR1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(votosBrancosR1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(votosNulosR1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segunda Ronda"));

    jLabel12.setText("Votos Brancos:");

    jLabel13.setText("Votos Nulos:");

    votosNulosR2.setText("0");

    votosBrancosR2.setText("0");

    jLabel10.setText("Número total de votos:");

    totalVotosR2.setText("0");

    candidatosR2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Candidato", "Nº Candidato", "Votos"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane2.setViewportView(candidatosR2);

    jLabel4.setText("Abstenção: ");

    abstencaoR2.setText("0%");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jScrollPane2)
            .addContainerGap())
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel10)
              .addComponent(jLabel12)
              .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(totalVotosR2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abstencaoR2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(votosNulosR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(votosBrancosR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))))))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(totalVotosR2)
          .addComponent(jLabel4)
          .addComponent(abstencaoR2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(votosBrancosR2)
          .addComponent(jLabel12))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(votosNulosR2)
          .addComponent(jLabel13))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vencedor"));

    vencedorTextField.setText("Fernando Manuel da Silva Ortiga");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(vencedorTextField)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(vencedorTextField)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(returnButton)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(returnButton)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /** Preencher campos de votos. */
  public void setResultados () {
    int idEleicao = eleicao.id();
    List<Candidato> votos1, votos2;
    DefaultTableModel dtm;
    
    // 1ª Ronda.
    totalVotosR1.setText("" + sge.votosTotaisPresidencial(idEleicao, 1));
    votosNulosR1.setText("" + sge.votosNulosPresidencial(idEleicao, 1));
    votosBrancosR1.setText("" + sge.votosBrancosPresidencial(idEleicao, 1));
    abstencaoR1.setText("" + sge.abstencaoPresidencial(idEleicao, 1) + "%");
    
    votos1 = sge.votosPorCandidatos(idEleicao, 1);
    dtm = (DefaultTableModel) candidatosR1.getModel();
    
    for (Candidato c : votos1)
      dtm.addRow(new Object[] {c.getNome(), c.getCC(), c.getVotos()});
    
    // Votos da 2ª ronda.
    totalVotosR2.setText("" + sge.votosTotaisPresidencial(idEleicao, 2));
    votosNulosR2.setText("" + sge.votosNulosPresidencial(idEleicao, 2));
    votosBrancosR2.setText("" + sge.votosBrancosPresidencial(idEleicao, 2));
    abstencaoR2.setText("" + sge.abstencaoPresidencial(idEleicao, 2) + "%");
    
    votos2 = sge.votosPorCandidatos(idEleicao, 2);
    dtm = (DefaultTableModel) candidatosR2.getModel();   
    
    for (Candidato c : votos2)
      dtm.addRow(new Object[] {c.getNome(), c.getCC(), c.getVotos()});
    
    // Vencedor.
    if (votos2.isEmpty()) {
      vencedorTextField.setText(votos1.get(0).getNome());
    } else {
      vencedorTextField.setText(votos2.get(0).getNome());
    }
      
  }

  /**
   * Voltar para o menu inicial.
   */
  private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
    // Voltar para o ecrã de login.
    Login login = new Login();
    login.setLocationRelativeTo(this);
    this.dispose();
    login.setVisible(true);
  }//GEN-LAST:event_returnButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
      javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (Exception ex) {
      System.out.println("Unable to load native look and feel");
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ResultadoPresidencial().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel abstencaoR1;
  private javax.swing.JLabel abstencaoR2;
  private javax.swing.JTable candidatosR1;
  private javax.swing.JTable candidatosR2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton returnButton;
  private javax.swing.JLabel totalVotosR1;
  private javax.swing.JLabel totalVotosR2;
  private javax.swing.JLabel vencedorTextField;
  private javax.swing.JLabel votosBrancosR1;
  private javax.swing.JLabel votosBrancosR2;
  private javax.swing.JLabel votosNulosR1;
  private javax.swing.JLabel votosNulosR2;
  // End of variables declaration//GEN-END:variables
}
