/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Business.Candidato;
import Business.SGE;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListSelectionModel;

/**
 *
 * @author joaocosta
 */
public class VotoPresidenciais extends javax.swing.JFrame {
  private final SGE sge;

  private final int ronda;
  private final int idEleicao;
  private final int idCidadao;
  private final List<Candidato> candidatos;

  /**
   * Creates new form Presidenciais
   */
  public VotoPresidenciais(SGE s, int idEleicao, int idCidadao, int ronda) {
    initComponents();
    this.sge        = s;
    this.ronda      = ronda;
    this.idEleicao  = idEleicao;
    this.idCidadao  = idCidadao;
    this.candidatos = new ArrayList<>();

    // Set window title.
    this.setTitle("Presidenciais");
    this.setListaCandidatos();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    voteButton = new javax.swing.JButton();
    votoBrancoButton = new javax.swing.JButton();
    votoNuloButton = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    optionsList = new javax.swing.JList();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(800, 600));

    voteButton.setText("Votar");
    voteButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        voteButtonActionPerformed(evt);
      }
    });

    votoBrancoButton.setText("Voto Branco");
    votoBrancoButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        votoBrancoButtonActionPerformed(evt);
      }
    });

    votoNuloButton.setText("Voto Nulo");
    votoNuloButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        votoNuloButtonActionPerformed(evt);
      }
    });

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidatos"));

    jScrollPane1.setViewportView(optionsList);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 473, Short.MAX_VALUE)
            .addComponent(votoNuloButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(votoBrancoButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(voteButton))
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(voteButton)
          .addComponent(votoBrancoButton)
          .addComponent(votoNuloButton))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /** Confirmar se o eleitor deseja votar na opção selecionada e em caso
     *  de resposta afirmativa registar o voto. */
  private void voteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteButtonActionPerformed
    String selecionado = (String) optionsList.getSelectedValue();
    int decisao = JOptionPane.showConfirmDialog(this,
        "Confirma que quer votar no candidato: " + selecionado + "?");

    if (decisao == JOptionPane.YES_OPTION) {
      // Registar voto.
      sge.votoPresidencial(idEleicao, sge.rondaMaisRecente(idEleicao), 
        idCidadao, candidatos.get(optionsList.getSelectedIndex()).getCC());
      
      // Voltar para o ecrã de Login.
      Login login = new Login();
      login.setLocationRelativeTo(this);
      this.dispose();
      login.setVisible(true);
    }
  }//GEN-LAST:event_voteButtonActionPerformed

  private void votoBrancoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votoBrancoButtonActionPerformed
    int d = JOptionPane.showConfirmDialog(this,
        "Tem a certeza que pretende votar em branco?");

    if (d == JOptionPane.YES_OPTION) {
      // Registar voto branco.
      sge.votoBrancoPresidencial(idEleicao,
          sge.rondaMaisRecente(idEleicao), idCidadao);

      // Voltar para o ecrã de Login.
      Login L = new Login();
      L.setLocationRelativeTo(this);
      this.dispose();
      L.setVisible(true);
    }
  }//GEN-LAST:event_votoBrancoButtonActionPerformed

  private void votoNuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votoNuloButtonActionPerformed
    int d = JOptionPane.showConfirmDialog(this,
        "Tem a certeza que pretende fazer voto nulo?");

    if (d == JOptionPane.YES_OPTION) {
      // Registar voto nulo.
      sge.votoNuloPresidencial(idEleicao,
          sge.rondaMaisRecente(idEleicao), idCidadao);

      // Regressar ao ecrã de Login.
      Login L = new Login();
      L.setLocationRelativeTo(this);
      this.dispose();
      L.setVisible(true);
    }
  }//GEN-LAST:event_votoNuloButtonActionPerformed

  /** Povoar lista com os nomes dos candidatos. */
  public void setListaCandidatos () {
    Collection<Candidato> aux   = sge.opcoesVotoPresidencial();
    DefaultListModel dlm        = new DefaultListModel();
    
    for (Candidato c : aux) candidatos.add(c);

    optionsList.setModel(dlm);

    for (Candidato c : this.candidatos) {
      dlm.addElement(c.getNome());
    }
  }

  /**
   * @param args the command line arguments
   */
  public void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
      javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
      System.setProperty("apple.laf.useScreenMenuBar", "true");
      System.setProperty("com.apple.mrj.application.apple.menu.about.name", "iVote");
    } catch (Exception ex) {
      System.out.println("Unable to load native look and feel");
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VotoPresidenciais(sge, idEleicao, idCidadao, ronda).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList optionsList;
  private javax.swing.JButton voteButton;
  private javax.swing.JButton votoBrancoButton;
  private javax.swing.JButton votoNuloButton;
  // End of variables declaration//GEN-END:variables
}
